# Generated by Django 2.1.7 on 2019-02-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190228_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncemail',
            name='sent_time',
            field=models.DateTimeField(null=True),
        ),
    ]
