# Generated by Django 2.1.7 on 2019-03-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190228_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttypes',
            name='can_geolocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounttypes',
            name='monthly_price',
            field=models.IntegerField(default=0, help_text='Monthly price in cents'),
        ),
        migrations.AddField(
            model_name='accounttypes',
            name='yearly_price',
            field=models.IntegerField(default=0, help_text='Yearly price in cents'),
        ),
    ]
