# Generated by Django 2.1.7 on 2019-03-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190310_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_selected',
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_websites',
            field=models.IntegerField(default=1, help_text='maximum number of websites that you can register'),
        ),
    ]
