# Generated by Django 2.1.7 on 2019-03-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190313_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='account_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
