# Generated by Django 2.1.7 on 2019-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190313_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_selected_signup',
            field=models.CharField(blank=True, help_text='The account type selected while signing up', max_length=50, null=True),
        ),
    ]
