# Generated by Django 3.0.6 on 2020-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20190314_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('website', models.CharField(max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sign_up_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
