# Generated by Django 2.1.7 on 2019-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='stripe_id',
            field=models.CharField(default='', help_text='Stripe ID for the test account', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='stripe_test_id',
            field=models.CharField(default='', help_text='Stripe ID for the test account', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
