# Generated by Django 2.1.7 on 2019-03-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePaymentIntent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('payment_intent_id', models.CharField(max_length=255)),
                ('payed', models.BooleanField(default=False)),
                ('payed_on', models.DateTimeField()),
                ('canceled', models.BooleanField(default=False)),
                ('canceled_on', models.DateTimeField()),
                ('amount', models.IntegerField(help_text='Amount in the minimum currency step')),
                ('currency', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
