# Generated by Django 2.1.7 on 2019-03-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_stripepaymentintent_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripepaymentintent',
            name='canceled_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stripepaymentintent',
            name='payed_on',
            field=models.DateTimeField(null=True),
        ),
    ]
