# Generated by Django 2.1.7 on 2019-03-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_stripepaymentintent_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepaymentintent',
            name='subscription_name',
        ),
    ]
