# Generated by Django 2.1.7 on 2019-03-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_messagestoadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagestoadmin',
            name='read_on',
            field=models.DateTimeField(null=True),
        ),
    ]
