# Generated by Django 2.1.7 on 2019-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20190225_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='referrer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
