# Generated by Django 2.1.7 on 2019-02-28 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20190228_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='raw_tracker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.RawTracker'),
        ),
    ]
