# Generated by Django 3.0.6 on 2020-05-24 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_tracker_raw_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawtracker',
            name='secret_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name='BeatTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('raw_tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beats', to='tracker.RawTracker')),
            ],
        ),
    ]
