# Generated by Django 3.0.6 on 2020-05-24 09:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20200524_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawtracker',
            name='secret_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
