# Generated by Django 3.0.6 on 2020-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20200524_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='session_length',
            field=models.IntegerField(default=0),
        ),
    ]
