# Generated by Django 3.1.12 on 2021-06-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_tracker_session_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='raw_tracker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.rawtracker'),
        ),
    ]
