# Generated by Django 3.1.12 on 2021-06-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20210620_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='raw_tracker',
        ),
    ]
